# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ximei(西梅)

on:
  workflow_dispatch:
  schedule:
     - cron: '2 1,2 * * *'
  watch:
    types: started
#env:
  #TZ: Asia/Shanghai

jobs:
  build1:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【西梅】'
        run: |
          node ximei.js
        env:
          XIMEI_HD: ${{ secrets.XIMEI_HD }}
          XIMEI_URL: ${{ secrets.XIMEI_URL }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN}}
          TG_USER_ID: ${{ secrets.TG_USER_ID}}
